name: sudut_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  modal_bottom_sheet:
  google_fonts:
  intl:
  provider: ^6.1.2
  blue_thermal_printer:
  fl_chart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
